### PR TITLE
AI API

### PR DESCRIPTION
**Pull request by ArmyofLight**
This commit contains the code to connect to the AI API and handle the result

### CODE REVIEW

**Review by sashacheek — CHANGES_REQUESTED** [review]
Put the gemini API key in a .env and add it to gitignore (if not already).

Add API key to repository secrets if you can, I'm not sure if you have permissions
https://github.com/sashacheek/bolt-brain/settings/secrets/actions/new

**Comment by ArmyofLight** [comment]
I can't access the link you shared so you might need to add it there. Also, I've not worked with .env so I'll look it up later. My approach isn't the most secure, but I'm focusing on speed over anything else at this point considering how little time we have left. I'll review this .env (environment variable?) when I can.

**Comment by sashacheek** [comment]
Ok I can add it then, no worries. I know one of the things we need to talk about in the final report is security so this could be one of the things we could talk about. Worse case scenario we could keep local copies of the api key to not push and have devops team handle it in prod since it’s more relevant for them

**Comment by ArmyofLight** [comment]
@sashacheek Hey Sasha! Great idea on the environment variable. I'll have to start using those at work too. I made the change and updated the code to point to the environment variable for the api key.

**Pull request merged**
